version: "3.8"
services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.03-py3  # Match with installed driver version
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/models
    command: tritonserver --model-repository=/models
    ports:
      - "8000:8000"  # gRPC
      - "8001:8001"  # HTTP
      - "8002:8002"  # Metrics

