FROM nvcr.io/nvidia/tritonserver:24.01-py3

# Install system dependencies for Prophet and build tools
RUN apt-get update && apt-get install -y python3-pip python3-venv gcc

# Install all required Python packages globally for all models
RUN pip install --upgrade pip && \
    pip install pandas prophet pydantic matplotlib 